name: flutter_carplay
description: Flutter Apps are now on Apple CarPlay. This package aims to make it safe to use iPhone apps made with Flutter in the car by integrating with CarPlay.
version: 1.0.3
homepage: https://github.com/oguzhnatly/flutter_carplay#readme
repository: https://github.com/oguzhnatly/flutter_carplay
issue_tracker: https://github.com/oguzhnatly/flutter_carplay/issues

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
